### ISSUE TITLE
Republish as public non-namespaced package on NPM registry

### ISSUE THREAD

**Issue by just214** [APSPhysics/eslint-config#11]
@papile -
I've learned through much trial and error that any namespaced packages publish on the Github registry still require an API key, which means setting up an `.npmrc` file for any projects that want to use that package. This can be a bit burdensome when you just want to spin up a front-end application.

I'd like to propose moving this package from the current namespaced Github package of `@apsphysics/eslint-config` to a public NPM package of `eslint-config-aps`. This would ensure that any frontend applications could use our linting rules without the overhead of setting up a Github API key and `.npmrc` file. This is especially useful when collaborating with an outside vendor like Phase 2, as is the case currently with the `aps-next` repo.

**Comment by papile** [comment]
I agree. There are many other companies that do it this way. So let's do it.

**Comment by just214** [comment]
Great, thanks!

**Comment by just214** [comment]
Done 👉🏻 https://www.npmjs.com/package/eslint-config-aps

I will write up an announcement once the new package is tested and everything is confirmed to work properly.
