### ISSUE TITLE
Proposal: Prevent Suppressed TS Errors in Production

### ISSUE THREAD

**Issue by mikeshort10** [APSPhysics/eslint-config#5]
## What 

Include the following rule in our ESLint config:

```json
{
 "rules": {
    "@typescript-eslint/ban-ts-comment": [
      2,
      { "ts-expect-error": "allow-with-description" }
    ]
}
```

## Why 

`@ts-ignore` allow errors to sneak into our code that could otherwise have been caught be TypeScript. It can be helpful during dev just to get things working, but it should never enter production code.

However, ignoring errors can be useful in rare cases. Some examples include:

- Third party libraries with incorrect types, but valid code
- Testing that incorrect arguments to a function are handled correctly or throw an Error

 In these cases, we should use `@ts-expect-error`. [The primary difference](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments) is that `@ts-ignore` will always ignore the error, but `@ts-expect-error` will notify developers if the underlying error has been resolved, e.g. if the external library updates its types. In this case, the code will still display a TS error, but this one indicating that the unused `@ts-expect-error` should be removed. 

Additionally, the `@ts-expect-error` comment must include a description, so that future developers can understand what the underlying issue was and how it might have been resolved.

## Resources

[TypeScript's own guidance on using the two suppressors](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#ts-ignore-or-ts-expect-error)

**Comment by just214** [comment]
I think this a great rule to include and the reasoning makes perfect sense to me. Feel free to create a PR if you'd like or I can make the change after we merge the current PR. Thanks!

**Comment by just214** [comment]
This rule has been added in v1.1.0 via PR #7. Thanks @mikeshort10!
